# Generated by Django 3.0.1 on 2020-04-22 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=20)),
                ('lista_max_items', models.SmallIntegerField(default=5)),
                ('lista_cycle_position', models.SmallIntegerField(default=4)),
                ('porcent_plataforma', models.SmallIntegerField(default=20)),
                ('porcent_patrocinador_directo', models.SmallIntegerField(default=20)),
                ('porcent_segunda_generacion', models.SmallIntegerField(default=3)),
                ('porcent_tercera_generacion', models.SmallIntegerField(default=7)),
                ('porcent_posicion_cobro', models.SmallIntegerField(default=50)),
                ('monto_minimo_retiro', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('comision_retiro', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('tope_cobros_nivel', models.SmallIntegerField(default=6)),
                ('tope_cobros_clon', models.SmallIntegerField(default=10)),
            ],
            options={
                'verbose_name_plural': 'Configuraciones',
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_activacion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('beneficios_totales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Cuentas',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.SmallIntegerField(default=-1)),
                ('posicion_cerrado', models.SmallIntegerField(default=-1)),
                ('color_cerrado', models.CharField(default='red', max_length=10)),
                ('cadena_ciclaje', models.TextField(blank=True, default='', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Juegos',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuevo', models.BooleanField(default=True)),
                ('whatsapp', models.CharField(blank=True, max_length=10, null=True)),
                ('celular', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Jugadores',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Niveles',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('A', 'ABONO'), ('P', 'PAGO'), ('R', 'RETIRO')], default='A', max_length=1)),
                ('descripcion', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cuenta')),
            ],
            options={
                'verbose_name_plural': 'Movimientos',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('items', models.SmallIntegerField(default=0)),
                ('estado', models.CharField(choices=[('A', 'ABIERTA'), ('C', 'CERRADA'), ('B', 'BLOQUEADA')], default='A', max_length=1)),
                ('pc', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('jugador', models.ManyToManyField(blank=True, default='', through='core.Juego', to='core.Jugador')),
                ('lista_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Lista')),
                ('nivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Nivel')),
            ],
            options={
                'verbose_name_plural': 'Listas',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='JugadorNivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('P', 'PENDIENTE DE ACTIVAR'), ('A', 'ACTIVO'), ('B', 'BLOQUEADO')], default='P', max_length=1)),
                ('n_referidos', models.SmallIntegerField(default=0)),
                ('n_referidos_activados', models.SmallIntegerField(default=0)),
                ('color', models.CharField(default='red', max_length=10)),
                ('ciclo', models.BigIntegerField(default=0)),
                ('cobros', models.BigIntegerField(default=0)),
                ('bloqueo_x_cobros_nivel', models.BooleanField(default=False)),
                ('bloqueo_y_cobros_clon', models.BooleanField(default=False)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Jugador')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Nivel')),
                ('patrocinador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patrocinador', to='core.Jugador')),
            ],
            options={
                'verbose_name_plural': 'Jugador Niveles',
            },
        ),
        migrations.AddField(
            model_name='jugador',
            name='nivel',
            field=models.ManyToManyField(blank=True, default='', through='core.JugadorNivel', to='core.Nivel'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='promotor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jugador_promotor', to='core.Jugador'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='juego',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Jugador'),
        ),
        migrations.AddField(
            model_name='juego',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Lista'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Jugador'),
        ),
        migrations.CreateModel(
            name='Cobrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('jugador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Jugador')),
                ('nivel', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Nivel')),
            ],
            options={
                'verbose_name_plural': 'Cobradores',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Clon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('P', 'PENDIENTE ACTIVAR'), ('A', 'ACTIVO')], default='P', max_length=1)),
                ('tipo', models.CharField(choices=[('R', 'POR REFERIDOS'), ('C', 'POR CICLOS')], default='R', max_length=1)),
                ('jugador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Jugador')),
                ('nivel', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Nivel')),
            ],
            options={
                'verbose_name_plural': 'Clones',
            },
        ),
    ]
