# Generated by Django 3.0.1 on 2020-05-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='estado',
            field=models.CharField(choices=[('R', 'REGISTRADO'), ('A', 'ACTIVO')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='tope_cobros_clon',
            field=models.SmallIntegerField(default=16),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='tope_cobros_nivel',
            field=models.SmallIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
