# Generated by Django 3.0.1 on 2019-12-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista',
            name='estado_der',
        ),
        migrations.RemoveField(
            model_name='lista',
            name='estado_izq',
        ),
        migrations.RemoveField(
            model_name='lista',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='lista',
            name='cycle_position',
            field=models.SmallIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='lista',
            name='max_items',
            field=models.SmallIntegerField(default=5),
        ),
    ]
