# Generated by Django 3.0.6 on 2020-06-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200508_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='concepto',
            field=models.CharField(blank=True, choices=[('C1', 'COMISION GENERACION 1'), ('C2', 'COMISION GENERACION 2'), ('C3', 'COMISION GENERACION 3'), ('CI', 'CICLAJE'), ('AC', 'ACTIVACION DE NIVEL'), ('CS', 'CARGA DE SALDO'), ('RS', 'RETIRO DE SALDO'), ('TS', 'TRANSFERENCIA DE SALDO'), ('RE', 'RETIRO')], default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(blank=True, choices=[('E', 'ENTRADA'), ('S', 'SALIDA')], default='', max_length=1, null=True),
        ),
    ]
