# Generated by Django 3.0.1 on 2020-04-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cobrador_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadornivel',
            name='bloqeo_x_cobros',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jugadornivel',
            name='bloqueo_x_clon',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clon',
            name='tipo',
            field=models.CharField(choices=[('R', 'POR REFERIDOS'), ('C', 'POR CICLOS')], default='R', max_length=1),
        ),
    ]
