# Generated by Django 3.0.1 on 2020-04-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200406_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
