# Generated by Django 3.0.3 on 2020-02-03 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cobrador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cobrador',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Cobradores'},
        ),
    ]
