# Generated by Django 3.0.6 on 2020-06-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200601_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='billetera',
            field=models.CharField(blank=True, choices=[('E', 'CRIPTOMONEDA EXTERNA'), ('D', 'DISPONIBLE'), ('A', 'ACTIVACION')], default='', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='concepto',
            field=models.CharField(blank=True, choices=[('C1', 'COMISION GENERACION 1'), ('C2', 'COMISION GENERACION 2'), ('C3', 'COMISION GENERACION 3'), ('CI', 'CICLAJE'), ('PN', 'PAGO POR NIVEL'), ('CS', 'CARGA DE SALDO'), ('RS', 'RETIRO DE SALDO'), ('TS', 'TRANSFERENCIA DE SALDO')], default='', max_length=2, null=True),
        ),
    ]
