# Generated by Django 3.0.1 on 2020-02-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200203_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='cadena_ciclaje',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
