# Generated by Django 3.0.1 on 2020-04-13 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200409_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugadornivel',
            old_name='bloqeo_x_cobros',
            new_name='bloqueo_x_cobros_nivel',
        ),
        migrations.RenameField(
            model_name='jugadornivel',
            old_name='bloqueo_x_clon',
            new_name='bloqueo_y_cobros_clon',
        ),
    ]
