# Generated by Django 3.0.3 on 2020-02-14 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200210_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelJuego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('P', 'PENDIENTE ACTIVAR'), ('A', 'ACTIVO')], default='P', max_length=1)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Juego')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Nivel')),
            ],
            options={
                'verbose_name_plural': 'NivelesJuegos',
            },
        ),
        migrations.AddField(
            model_name='juego',
            name='nivel',
            field=models.ManyToManyField(through='core.NivelJuego', to='core.Nivel'),
        ),
    ]
