# Generated by Django 3.0.1 on 2020-04-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200412_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracion',
            old_name='tope_cobros',
            new_name='tope_cobros_nivel',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='tope_cobros_clon',
            field=models.SmallIntegerField(default=12),
        ),
    ]
