# Generated by Django 3.0.1 on 2020-04-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200413_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadornivel',
            name='cobros',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='tope_cobros_clon',
            field=models.SmallIntegerField(default=10),
        ),
    ]
