# Generated by Django 3.0.1 on 2020-02-21 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200213_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='clon',
            name='tipo',
            field=models.CharField(choices=[('P', 'PENDIENTE ACTIVAR'), ('A', 'ACTIVO')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='lista',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Nivel'),
        ),
        migrations.AlterField(
            model_name='niveljuego',
            name='estado',
            field=models.CharField(choices=[('P', 'PENDIENTE ACTIVAR'), ('A', 'ACTIVO')], default='A', max_length=1),
        ),
    ]
