# Generated by Django 3.0.1 on 2020-02-21 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200220_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='JugadorNivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Jugador')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Nivel')),
            ],
            options={
                'verbose_name_plural': 'Jugador Niveles',
            },
        ),
        migrations.RemoveField(
            model_name='juego',
            name='nivel',
        ),
        migrations.DeleteModel(
            name='NivelJuego',
        ),
    ]
