# Generated by Django 3.0.1 on 2020-02-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200221_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='nivel',
            field=models.ManyToManyField(blank=True, default='', through='core.JugadorNivel', to='core.Nivel'),
        ),
    ]
