# Generated by Django 3.0.1 on 2020-02-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_jugador_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadornivel',
            name='estado',
            field=models.CharField(choices=[('P', 'PENDIENTE DE ACTIVAR'), ('A', 'ACTIVO'), ('B', 'BLOQUEADO')], default='P', max_length=1),
        ),
    ]
