# Generated by Django 3.0.1 on 2020-02-28 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_jugadornivel_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcent_plataforma', models.SmallIntegerField(default=20)),
                ('porcent_patrocinador_directo', models.SmallIntegerField(default=20)),
                ('porcent_segunda_generacion', models.SmallIntegerField(default=3)),
                ('porcent_tercera_generacion', models.SmallIntegerField(default=7)),
                ('porcent_posicion_cobro', models.SmallIntegerField(default=50)),
                ('monto_minimo_retiro', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('comision_retiro', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Contabilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('tipo', models.CharField(choices=[('A', 'ABONO POR ACTIVACION'), ('C', 'ABONO POR CARGUE')], default='A', max_length=1)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Jugador')),
            ],
        ),
    ]
