# Generated by Django 3.0.1 on 2020-02-28 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_configuracion_contabilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_activaciones', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo_acumulado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ganancias_totales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('A', 'ABONO POR ACTIVACION'), ('C', 'ABONO POR CARGUE')], default='A', max_length=1)),
                ('descripcion', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cuenta')),
            ],
        ),
        migrations.AddField(
            model_name='configuracion',
            name='inicio_juego',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Contabilidad',
        ),
    ]
