# Generated by Django 3.0.1 on 2020-02-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200228_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta',
            options={'ordering': ['created'], 'verbose_name_plural': 'Cuentas'},
        ),
        migrations.AlterModelOptions(
            name='movimientos',
            options={'ordering': ['created'], 'verbose_name_plural': 'Movimientos'},
        ),
        migrations.RemoveField(
            model_name='lista',
            name='cycle_position',
        ),
        migrations.RemoveField(
            model_name='lista',
            name='max_items',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='lista_cycle_position',
            field=models.SmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='lista_max_items',
            field=models.SmallIntegerField(default=5),
        ),
    ]
