# Generated by Django 3.0.1 on 2020-02-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200228_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='tope_cobros',
            field=models.SmallIntegerField(default=6),
        ),
    ]
