# Generated by Django 3.0.1 on 2020-02-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_configuracion_tope_cobros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracion',
            options={'verbose_name_plural': 'Configuraciones'},
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='inicio_juego',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='nombre',
            field=models.CharField(default='', max_length=20),
        ),
    ]
