# Generated by Django 3.0.1 on 2020-03-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_nivel_indice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='ganancias_totales',
            new_name='beneficios_totales',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='saldo_activaciones',
            new_name='saldo_activacion',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='saldo_acumulado',
            new_name='saldo_disponible',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='saldo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
