# Generated by Django 3.0.1 on 2020-03-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200303_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
